export enum ActionTypes {
  ADD_USER,
  AUTHENTICATE,
  GET_SERIES_BY_ID,
  GET_SERIES_LIST,
  GET_SERIES_LIST_BY_USERNAME,
  DELETE_SERIES,
  ADD_SERIES_WITH_USERNAME,
  UPDATE_SERIES_WITH_USERNAME,
  GET_EVENT_BY_SERIES_ID,
  DELETE_EVENT
}
